RETURN 
    true or false,
//       ^ operator
    false xor false,
//        ^ operator
    true and false,
//       ^ operator
    not false,
//  ^ operator
    1 = 2,
//    ^ operator
    1 <> 2,
//    ^ operator
    1 > 2,
//    ^ operator
    1 < 2,
//    ^ operator
    1 >= 2,
//    ^ operator
    1 <= 2,
//    ^ operator
    1 - 2,
//    ^ operator
    1 + 2,
//    ^ operator
    1 * 2,
//    ^ operator
    1 / 2,
//    ^ operator
    1 % 2,
//    ^ operator
    1 ^ 2;
//    ^ operator

